import {env} from 'cloudflare:workers';
export type Paper={id:string;title:string;headline?:string;doi?:string;url:string;date:string;journal:string;team:string;abstract?:string;news?:string;limitation?:string;code?:string;codeUrl?:string;citations:number|null;citationSource?:string;citationUrl?:string;citationDate?:string;topic:string;curated?:boolean;evidence?:string;publicationType?:string;discovered?:string};
const defaults={topics:[{name:'脊柱影像与智能测量',query:'spine vertebral segmentation Cobb angle'},{name:'医学影像基础模型',query:'medical imaging foundation model'},{name:'脊柱生物力学',query:'spine finite element surrogate'}],lastUpdate:null,schedule:'尚未启用',timezone:'Asia/Shanghai'};
function db(){const x=(env as any).DB;if(!x)throw new Error('数据服务暂不可用，请稍后重试');return x;}
export async function get(id:string){const r=await db().prepare('SELECT data FROM records WHERE id = ?').bind(id).first();return r?JSON.parse(r.data):null;}
export async function put(id:string,kind:string,data:any){await db().prepare('INSERT INTO records (id,kind,data,updated_at) VALUES (?,?,?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data, updated_at=excluded.updated_at').bind(id,kind,JSON.stringify(data),new Date().toISOString()).run();return data;}
export async function list(kind:string){const r=await db().prepare('SELECT data FROM records WHERE kind = ? ORDER BY updated_at DESC LIMIT 500').bind(kind).all();return r.results.map((x:any)=>JSON.parse(x.data));}
function str(x:any,n=100000){if(typeof x!=='string'||x.length>n)throw new Error('文字字段格式或长度不正确');return x;}
function safeURL(x:any){const u=new URL(str(x,2000));if(u.protocol!=='https:'&&u.protocol!=='http:')throw new Error('链接必须为http或https');return u.href;}
export async function snapshot(){return{papers:await list('paper'),states:await list('state'),settings:(await get('settings'))||defaults};}
export async function action(name:string,a:any={}){
 if(name==='get_workspace')return snapshot();
 if(name==='get_paper'){const p=await get('paper:'+str(a.id,300));if(!p)throw new Error('论文不存在');return{paper:p,state:await get('state:'+a.id)};}
 if(name==='save_settings'){if(!Array.isArray(a.topics)||a.topics.length<1||a.topics.length>8)throw new Error('请设置1–8个研究方向');const topics=a.topics.map((t:any)=>({name:str(t.name,100).trim(),query:str(t.query,250).trim()}));if(topics.some((t:any)=>!t.name||!t.query))throw new Error('研究方向和检索词不能为空');return put('settings','settings',{...((await get('settings'))||defaults),topics});}
 if(name==='set_schedule_status'){return put('settings','settings',{...((await get('settings'))||defaults),schedule:str(a.status,300)});}
 if(name==='ingest_papers'){if(!Array.isArray(a.papers)||a.papers.length>100)throw new Error('每批最多100篇');for(const x of a.papers){const id=str(x.doi||x.id,300).toLowerCase().replace(/^https?:\/\/(dx\.)?doi.org\//,'');const old=await get('paper:'+id);const p={...old,...x,id,title:str(x.title,1500),url:safeURL(x.url),citations:typeof x.citations==='number'?x.citations:null,discovered:old?.discovered||new Date().toISOString()};await put('paper:'+id,'paper',p);}const settings=(await get('settings'))||defaults;await put('settings','settings',{...settings,lastUpdate:new Date().toISOString(),lastNew:a.papers.length});return{saved:a.papers.length};}
 if(name==='refresh_sources')return refresh();
 const id=str(a.id,300);const p=await get('paper:'+id);if(!p)throw new Error('论文不存在');const key='state:'+id;const s=(await get(key))||{id,saved:false,status:'new'};
 if(name==='set_saved')return put(key,'state',{...s,saved:!!a.saved});
 if(name==='request_reading'){if(s.status==='reading_requested'||s.reading)return s;return put(key,'state',{...s,saved:true,status:'reading_requested',requestedAt:new Date().toISOString()});}
 if(name==='complete_reading'){if(!['full_text','uploaded_pdf'].includes(a.evidence))throw new Error('精读必须基于全文或上传PDF，不能用摘要替代');if(!Array.isArray(a.sources)||!a.sources.length)throw new Error('需要可核查来源');if(s.status!=='reading_requested')throw new Error('必须先请求精读');return put(key,'state',{...s,status:'reading_ready',reading:str(a.markdown),readingSources:a.sources.map(safeURL),evidence:a.evidence,readingAt:new Date().toISOString(),approved:false});}
 if(name==='report_reading_blocker'){return put(key,'state',{...s,status:'needs_fulltext',blocker:str(a.message,2000)});}
 if(name==='approve_article'){if(!s.reading)throw new Error('请先完成并阅读精读报告');if(a.confirm!==true)throw new Error('需要明确确认精读结果后才能制作稿件');return put(key,'state',{...s,approved:true,approvedAt:new Date().toISOString(),status:'article_requested'});}
 if(name==='complete_article'){if(!s.approved||s.status!=='article_requested')throw new Error('用户尚未确认开始制作推文');return put(key,'state',{...s,status:'article_ready',article:str(a.markdown),articleAt:new Date().toISOString()});}
 if(name==='save_note')return put(key,'state',{...s,note:str(a.note,20000)});
 throw new Error('未知操作');
}
async function refresh(){const settings=(await get('settings'))||defaults;const since=new Date(Date.now()-30*86400000).toISOString().slice(0,10);const today=new Date().toISOString().slice(0,10);let all:Paper[]=[];let warnings:string[]=[];
 for(const t of settings.topics){try{const u=new URL('https://api.crossref.org/works');u.searchParams.set('query',t.query);u.searchParams.set('filter',`from-pub-date:${since},until-pub-date:${today},type:journal-article`);u.searchParams.set('rows','20');u.searchParams.set('sort','published');u.searchParams.set('order','desc');const r=await fetch(u,{headers:{'User-Agent':'xuelab-literature/1.0'},signal:AbortSignal.timeout(18000)});if(!r.ok)throw new Error(`Crossref ${r.status}`);const j:any=await r.json();for(const x of j.message.items){if(!x.DOI||!x.title?.[0])continue;const parts=x.published?.['date-parts']?.[0]||[];const authors=(x.author||[]).slice(0,3).map((v:any)=>[v.given,v.family].filter(Boolean).join(' ')).join('、');const inst=[...new Set((x.author||[]).flatMap((v:any)=>(v.affiliation||[]).map((z:any)=>z.name)))].slice(0,4).join('；');all.push({id:x.DOI.toLowerCase(),doi:x.DOI,title:x.title[0],url:x.URL||'https://doi.org/'+x.DOI,date:parts.map((v:any,i:number)=>i?String(v).padStart(2,'0'):v).join('-'),journal:x['container-title']?.[0]||'待核实',team:authors+(inst?'｜'+inst:'｜机构待核实'),abstract:(x.abstract||'').replace(/<[^>]+>/g,' '),citations:typeof x['is-referenced-by-count']==='number'?x['is-referenced-by-count']:null,citationSource:'Crossref',citationUrl:'https://api.crossref.org/works/'+encodeURIComponent(x.DOI),citationDate:today,topic:t.name,evidence:'元数据 / 摘要，未经全文精读',code:'待核实',publicationType:'期刊论文',curated:false});}}catch(e){warnings.push(t.name+'：'+(e as Error).message);}}
 const unique=[...new Map(all.map(p=>[p.id,p])).values()];let added=0;for(const p of unique){const old=await get('paper:'+p.id);if(!old){await put('paper:'+p.id,'paper',{...p,discovered:new Date().toISOString()});added++;}else await put('paper:'+p.id,'paper',{...old,citations:p.citations,citationSource:p.citationSource,citationUrl:p.citationUrl,citationDate:p.citationDate});}
 await put('settings','settings',{...settings,lastAttempt:new Date().toISOString(),lastUpdate:warnings.length===settings.topics.length?settings.lastUpdate:new Date().toISOString(),lastNew:added,warnings});return{added,candidates:unique.length,warnings,note:'检索候选待相关性核验，早报由助手审核后写入'};}
